import string
import os
import re
from xml.etree import ElementTree as ET
from xml.dom import minidom

class DefaultFormatter(string.Formatter):
    def __init__(self, default=''):
        self.default = default
    
    def get_field(self, field_name, args, kwargs):
        try:
            return super().get_field(field_name, args, kwargs)
        except (KeyError, AttributeError):
            return self.default

def upperfirst(word):
    return word[0].upper() + word[1:]

def lowerfirst(word):
    return word[0].lower() + word[1:]

def merge_xml_files(existing_path, new_xml_string):
    """
    Merges new_xml_string into the file at existing_path.
    Returns the merged XML string.
    """
    try:
        # Register namespace to prevent ns0 prefixes
        ET.register_namespace('', "http://www.w3.org/2001/XMLSchema-instance")
        
        # Parse existing file
        tree = ET.parse(existing_path)
        root = tree.getroot()
        
        # Parse new content
        new_root = ET.fromstring(new_xml_string)
        
        if root.tag != new_root.tag:
            return new_xml_string

        # Merge new_root children into root
        _merge_elements(root, new_root)
        
        # Convert back to string (pretty print)
        rough_string = ET.tostring(root, 'utf-8')
        reparsed = minidom.parseString(rough_string)
        
        # Cleanup Whitespace: Remove empty lines generated by minidom
        pretty_xml = reparsed.toprettyxml(indent="    ")
        cleaned_lines = [line for line in pretty_xml.split('\n') if line.strip()]
        return '\n'.join(cleaned_lines)
        
    except Exception as e:
        print(f"Warning: XML Merge failed ({e}). Overwriting.")
        return new_xml_string

def _get_element_id(elem):
    """Identify elements by specific attributes for merging."""
    # Added 'for' to support <preference for="..." /> uniqueness
    for attr in ['id', 'name', 'frontName', 'url', 'class', 'instance', 'for']:
        if attr in elem.attrib:
            return f"{elem.tag}[@{attr}='{elem.attrib[attr]}']"
    return elem.tag

def _merge_elements(base_elem, new_elem):
    # Map existing children by ID
    existing_map = {}
    for child in base_elem:
        ident = _get_element_id(child)
        # Handle duplicate keys in base (e.g. if XML is already malformed or has duplicates)
        # We store the *first* occurrence to merge into, or use a list if needed.
        # For simplicity, last wins in map, but we iterate base_elem to preserve order if needed?
        # Actually, if we want to support multiple distinct preferences, ident includes the value.
        # So "preference[@for='A']" is different from "preference[@for='B']".
        existing_map[ident] = child
    
    for new_child in new_elem:
        ident = _get_element_id(new_child)
        
        if ident in existing_map:
            # Recursively merge matches
            target = existing_map[ident]
            # Merge attributes
            target.attrib.update(new_child.attrib)
            # If element has text content and no children, update text
            if not list(new_child) and new_child.text:
                target.text = new_child.text
            # Recurse
            _merge_elements(target, new_child)
        else:
            # Append new child
            base_elem.append(new_child)

def to_pascal_case(snake_str):
    """Converts snake_case or sentence string to PascalCase."""
    components = snake_str.replace(' ', '_').split('_')
    return "".join(x.title() for x in components)